## Challenge: Generate NumPy arrays using functions like np.arange(), np.linspace(), and np.random.

## Why NumPy arrays?

NumPy (Numerical Python) is a fundamental library in the Python ecosystem for **numerical and scientific computing.**

It provides support for working with large, **multi-dimensional arrays and matrices**, along with a collection of mathematical functions to operate on these arrays efficiently.

These arrays are more **memory-efficient and faster to manipulate** than standard Python lists or arrays.

## Importing NumPy bibrary

In [1]:
import numpy as np

## 1.Using np.arange()

**np.arange(start, stop, step)** generates evenly spaced values within a specified range.

In [2]:
arr1 = np.arange(0,10,2)
arr1

array([0, 2, 4, 6, 8])

## 2.Using np.linspace():

**np.linspace(start, stop, num)** generates num evenly spaced values over the specified range.

In [3]:
arr2 = np.linspace(0,1,5)
arr2

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
arr2 = np.linspace(-2, 2, 20, endpoint=False)
arr2

array([-2. , -1.8, -1.6, -1.4, -1.2, -1. , -0.8, -0.6, -0.4, -0.2,  0. ,
        0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8])

## 3.Using np.random

NumPy's random module provides various functions for generating random arrays.

**To generate random integers within a range**

In [5]:
rand_integers = np.random.randint(1, 100, size=5)  # Generates 5 random integers between 1 and 100
rand_integers

array([42, 56, 14, 70, 23])

**To generate random floating-point numbers from a uniform distribution**

In [6]:
rand_uniform = np.random.uniform(0, 1, size=3)  # Generates 3 random floats between 0 and 1
rand_uniform

array([0.45694842, 0.67470975, 0.2641699 ])

**To generate random numbers from a normal distribution (Gaussian)**

In [7]:
rand_normal = np.random.normal(0, 1, size=4)  # Generates 4 random numbers from a standard normal distribution
rand_normal

array([-3.12577823,  0.0744072 ,  1.46907653,  0.32915719])