## Challenge: Rotate an NxN matrix (2D array) 90 degrees clockwise.

## What is a matrix?

A matrix is often represented as a two-dimensional array. This two-dimensional array structure is used to store and manipulate data in a tabular format with rows and columns. Each element of the two-dimensional array represents a cell in the matrix.

## Input

In [3]:
matrix1 =[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


# After rotating 90 degrees clockwise, it should become:

# expected_output1 = 
# [
#   [7, 4, 1],
#   [8, 5, 2],
#   [9, 6, 3]
# ]

## Traditional solution

In [1]:
def rotate(matrix):
    n = len(matrix)

    # Step 1: Transpose the matrix
    
    for i in range(n):
        for j in range(i, n):
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]

    # Step 2: Reverse each row of the transposed matrix
    
    for i in range(n):
        matrix[i].reverse()

In [4]:
rotate(matrix1)

In [6]:
for row in matrix1:
    print(row)

[7, 4, 1]
[8, 5, 2]
[9, 6, 3]


## Using Numpy

NumPy, short for "Numerical Python," is a powerful Python library for numerical and scientific computing.

It provides support for arrays, matrices, and a wide range of mathematical functions to work with these data structures efficiently.

In [7]:
import numpy as np

def rotate_matrix_90_degrees(matrix):
    # Convert the input list into a NumPy array
    arr = np.array(matrix)

    # Transpose the array to swap rows and columns
    transposed = arr.transpose()

    # Reverse each row to achieve the 90-degree clockwise rotation
    rotated = np.flip(transposed, axis=1)

    return rotated

In [8]:
rotated_matrix = rotate_matrix_90_degrees(matrix1)
print(rotated_matrix)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [9]:
%timeit rotate(matrix1)

1.95 µs ± 46.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
%timeit rotate_matrix_90_degrees(matrix1)

4.94 µs ± 21 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
